### ISSUE TITLE
Can't change background-color on a-gui-label with setAttribute

### ISSUE THREAD

**Issue by mauriciomartinez-itesm** [rdub80/aframe-gui#15]
There is no way to change the color of the label with the setAttribute method.

This doesn't work:
`aGuiLbelElement.setAttribute("background-color", "red");`

This works:
`aGuiLbelElement.setAttribute("material", "color:red");`

**Comment by lmalave** [comment]
This is now fixed in version 0.2.1.   Setting an attribute on the label triggers a redraw of the label.
