### ISSUE TITLE
Circle timer value does not update

### ISSUE THREAD

**Issue by rdub80** [rdub80/aframe-gui#23]
In my branch: https://github.com/rdub80/aframe-gui/tree/new-animation-plugin

https://github.com/rdub80/aframe-gui/blob/new-animation-plugin/src/scripts/vars.js#L31
drawText() function does not update the updated timer value

update function does work but not for text.

https://github.com/rdub80/aframe-gui/blob/new-animation-plugin/src/components/circle-timer.js#L113

**Comment by lmalave** [comment]
I included this in the latest pull request.

**Comment by lmalave** [comment]
This has been fixed as of version 0.3.3
