### ISSUE TITLE
Compatibility with a-frame 0.9.0

### ISSUE THREAD

**Issue by vladern** [rdub80/aframe-gui#26]
Compatibility with a-frame 0.9.0 is broken, icons is not loading and text does not appear.

Steps to reproduce
* set up Angular 6 + a-frame on version 0.9.0
* use aframe-gui component

**Comment by mauriciomartinez-itesm** [comment]
There's no need to set up Angular, it doesn't work with plain a-frame either

**Comment by lmalave** [comment]
Please check now - this should be fixed in the latest version 0.3.1.

**Comment by vladern** [comment]
I tryed on version 0.3.1 and buttons text now apears, but now all text do not response to property font-size, labels text are gigant and button text are verry smole. That hapens with 0.3.1 version in 0.8.1  aframe version too.

**Comment by lmalave** [comment]
Very sorry about that - I fixed the issue with labels responding to font-size attribute.   Please take a look at 0.3.2

**Comment by lmalave** [comment]
I am still trying to figure out why the text size for labels is different than for buttons, but at least it's responding to the font-size attribute so you can just make the font size smaller for labels.

**Comment by lmalave** [comment]
Ok, the label font sizes have also been fixed in 0.3.3 to match the size of the fonts for the other components.
