### ISSUE TITLE
input component mislabled in the Docs

### ISSUE THREAD

**Issue by renman87** [rdub80/aframe-gui#27]
In the documentation, in the part where the api for the components are explained,
a-gui-icon-label-button Component 's example text is unexpectedly repeated.
where in the next section, a-gui-input Component,
the api is correct, but the example text is 
a-gui-icon-label-button
	width="2.5" height="0.75"
	onclick="buttonActionFunction"
	icon="social-github"
	value="label button"
	font-family="Arial"
	margin="0 0 0.05 0"
/a-gui-icon-label-button
where it should be
a-gui-input
	width="2.5" height="0.75"
	onclick="buttonActionFunction"
	value="label button"
	font-family="Arial"
	margin="0 0 0.05 0"
/a-gui-input
or something to that effect.

**Comment by rdub80** [comment]
thanks good catch!
