### ISSUE TITLE
Touch & Mouse clickable

### ISSUE THREAD

**Issue by smxthereisonlyone** [rdub80/aframe-gui#35]
Hello,

I love your UI elements!

How would it be possible to make the ui elements clickable with touch input on mobile and mouse click on desktop?

Thanks!

**Comment by rdub80** [comment]
Hi Stefan, 
you can make the elements clickable on mouse/touch input by defining rayOrigin mouse in the scene element. 
Like this:
 `<a-scene cursor="rayOrigin: mouse" raycaster="objects: [gui-interactable]">`
