### ISSUE TITLE
aframe-gui compatibility issue aframe 1.0.3

### ISSUE THREAD

**Issue by igmixer** [rdub80/aframe-gui#39]
Currently using aframe version 1.0.3 but my gui animation for the cursor is not reading properly and getting the error attached. Any help or direction would be much appreciated.
![animationError](https://user-images.githubusercontent.com/60496141/74004520-95012600-493b-11ea-824d-dc1914af7465.PNG)

**Comment by rdub80** [comment]
bug fixed
