### ISSUE TITLE
i open de example and the gui does not show 

### ISSUE THREAD

**Issue by CamiloB** [rdub80/aframe-gui#4]
hi i use the same code i literaly copy and paste the code from you example https://github.com/rdub80/aframe-gui/blob/master/examples/all_components.html

but only show this 

<img width="1219" alt="captura de pantalla 2017-10-15 a la s 4 25 30 p m" src="https://user-images.githubusercontent.com/6754789/31589340-828041c4-b1c5-11e7-9fa8-c13b8f3e8b03.png">

the GUI never appear ill try a lot of thing please help

**Comment by rdub80** [comment]
@CamiloB Thanks for pointing this out! @lmalave could you check into the aframe-gui.min.js distribution - I believe the issue might be there

**Comment by rdub80** [comment]
@CamiloB can you share your code somewhere? looks like <a-gui-flex-container> and its content get ignored.

**Comment by lmalave** [comment]
@rdub80 I posted a new dist.

**Comment by CamiloB** [comment]
hi thanks a lot its working now when you post the new dist
