### ISSUE TITLE
I want to call a phone from the gui

### ISSUE THREAD

**Issue by CamiloB** [rdub80/aframe-gui#6]
Hi i want to know how to invoque de phone call in a gui button, i try to use like i used to do on html only using `href="tel:+573017828978"`  but nothing happen can you please help me whit this ? thanks a lot 
`		<a-gui-flex-container
			flex-direction="column" justify-content="center" align-items="normal" component-padding="0.1" 
			opacity="0.7" width="3" height="2"
			position="-1.75 2 -5" rotation="0 0 0"
		>
			<a-gui-label width="2.5" height="0.75"
						value="Llama ahora"
						font-family="Arial"
			>
			</a-gui-label>
			<a-gui-input width="3" height="0.75"
						onclick="testInputAction"
						font-family="Arial"
						value="+573017828978"
						href="tel:+573017828978"
			>
			</a-gui-input>
						<a-gui-icon-button
				height="0.75"
				onclick="call"
				icon="android-call"
				href="tel:+573017828978"
			>
			</a-gui-icon-button>
		</a-gui-flex-container>`

**Comment by rdub80** [comment]
Hi Camilo, 
if you want to use your smart phone to dial that number you have to add a script to define the `callFunction` function 

```
<a-gui-flex-container flex-direction="column" justify-content="center" align-items="normal" component-padding="0.1" opacity="0.7" width="3" height="2" position="-1.75 2 -5" rotation="0 0 0" > 
    <a-gui-label width="2.5" height="0.75" value="Llama ahora" font-family="Arial" >
    </a-gui-label> 
    <a-gui-input id="myNumber" width="3" height="0.75" font-family="Arial" value="+573017828978" > 
    </a-gui-input> 
    <a-gui-icon-button height="0.75" onclick="callFunction" icon="android-call"> 
    </a-gui-icon-button> 
</a-gui-flex-container>
```

Place this script before the body tag:
```
<script>
window.callFunction = function(){
  var my_number = document.getElementById("myNumber");
  var number = my_number.getAttribute("val"); 
//  var number = "+573017828978"; 
  var call_number = window.open("tel:"+number, "_blank"); // _blank keeps VR-mode alive
  call_number.close();  // closes removes the new window / browser tab
}
</script>
```

Be aware that the display of your mobile device will be taken over by the built-in call app. If you want to keep the VR scene active and the call to happen in the background of the A-Frame experience you should look into VOIP provider JS SDKs:

- https://www.twilio.com/webrtc
- https://www.sinch.com/tutorials/turn-browser-phone-js-sdk/
- https://www.plivo.com/docs/sdk/web/
- and many more

**Comment by CamiloB** [comment]
hi i already solve the problem like this, i use your solution but does not work for my, bellow i put the link if you want to try it, thanks a lot

`<a-gui-icon-button
				height="0.75"
				onclick="window.open('tel:3017828978');"
				icon="android-call">
</a-gui-icon-button>`

[http://vr.ninus.co/vrstate/](url)

**Comment by CamiloB** [comment]
never mind i change this for you scrip and works really great 

`<script>
	window.callFunction = function(){
  	var my_number = document.getElementById("myNumber");
  	 var number = "+573017828978"; 
  	var call_number = window.open("tel:"+number, "_blank"); // _blank keeps VR-mode alive
  	call_number.close();  // closes removes the new window / browser tab
	}
	</script>`

**Comment by rdub80** [comment]
awesome!
